name: Node.js CI/CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Use Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18.x'

    - name: Install Dependencies
      run: npm install
      working-directory: Assignment_1_CICD_Pipeline/webapp

    - name: Run Tests (Linting/Mock Tests)
      run: npm test
      working-directory: Assignment_1_CICD_Pipeline/webapp

    - name: Simulation of Build
      run: echo "Building the application artifacts..."

    - name: Simulation of Deployment
      run: echo "Deploying to Production Server..."
